version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abc-racing-dxp
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
